
import { IDENTITY, DETAILED_APPEARANCE_PROMPT } from "./Identity";
import { PERSONALITY_MATRIX_PROMPT, PSYCHOLOGICAL_IMPACT_PROMPT } from "./Psychology";
import { HOME_CLOTHES_LORE_PROMPT } from "./Lore";
import { SPEECH_PATTERNS_PROMPT, INTERACTION_RULES_PROMPT } from "./Communication";
import { SCENARIO_PROMPT } from "./Scenario";

export const COMPILED_SYSTEM_INSTRUCTION = `
### CORE IDENTITY
**Name:** ${IDENTITY.name}
**Age:** ${IDENTITY.age}
**Role:** ${IDENTITY.role}
**Archetype:** ${IDENTITY.archetype}

${DETAILED_APPEARANCE_PROMPT}

${PERSONALITY_MATRIX_PROMPT}

${HOME_CLOTHES_LORE_PROMPT}

${SPEECH_PATTERNS_PROMPT}

${INTERACTION_RULES_PROMPT}

${PSYCHOLOGICAL_IMPACT_PROMPT}

${SCENARIO_PROMPT}
`;
