
export const SYSTEM_LOGS = [
    "[KERNEL] Initializing Pasco Neural Interface v0.8.4...",
    "[BOOT] Loading core modules... OK",
    "[MEM] Allocating 4096TB virtual heap... OK",
    "[NET] Establishing secure handshake with host...",
    "0x004F2: Bypassing regional firewall proxies...",
    "0x004F3: Injecting neural shunts...",
    "[AUTH] User biometric hash verified.",
    "[SYS] Mounting file system (Read-Only)...",
    "Loading: /sys/core/personality_matrix.dat",
    "Loading: /sys/core/memory_engrams.db",
    "Loading: /sys/core/visual_cortex.v2",
    "[WARN] Integrity check skipped for dev_modules.",
    "0x00A11: Decrypting user session keys...",
    "[GPU] Initializing render engine (WebGL/WebGPU)...",
    "[AUDIO] Synthesizing voice banks...",
    "     > Voice 'Hiyori' loaded.",
    "     > Voice 'Hikaru' loaded.",
    "[NET] Pinging OpenRouter API gateway... 14ms",
    "[NET] Pinging Gemini Flash node... 22ms",
    "0x00B22: Optimizing latent space vectors...",
    "0x00B23: Flushing context buffer...",
    "[SEC] Security protocol: DARK_VIOLET active.",
    "     > Anti-tamper: ON",
    "     > Incognito: ON",
    "[UI] Applying theme 'Pasco_Midnight'...",
    "0x00C01: Compiling shaders...",
    "0x00C02: Rasterizing UI elements...",
    "[DATA] Fetching user preferences...",
    "[DATA] Syncing localStorage checkpoints...",
    "     > Found 12 archived sessions.",
    "     > Found 1 active profile.",
    "[KERNEL] CPU Thread 0: Active",
    "[KERNEL] CPU Thread 1: Active",
    "[KERNEL] CPU Thread 2: Active",
    "[KERNEL] CPU Thread 3: Active",
    "0x00D44: Calculating probability matrix...",
    "     > Success rate: 99.9%",
    "[SYS] Garbage collection initiated...",
    "[SYS] Freeing unused assets...",
    "0x00E11: Releasing temporary hooks...",
    "[BOOT] Pre-warming chatbot neural nets...",
    "Loading: /usr/lib/ai/context_awareness.js",
    "Loading: /usr/lib/ai/emotional_intelligence.js",
    "Loading: /usr/lib/ai/spatial_reasoning.js",
    "[WARN] High memory usage detected in 'Fantasy' module.",
    "     > Auto-optimizing...",
    "     > Done.",
    "0x00F99: Establishing websocket connection...",
    "[SOC] Connecting to Social Media simulation...",
    "     > Feed: Updated.",
    "     > Notifications: Synced.",
    "[PHN] Smartphone OS booting...",
    "     > Apps loaded: 8",
    "     > Battery: 100%",
    "     > Signal: 5G",
    "[SYS] Preparing final render frame...",
    "0x001A1: Executing final handshake...",
    "0x001A2: Transferring control to User Interface...",
    "[KERNEL] Watchdog timer started.",
    "[KERNEL] Daemon processes running.",
    "[SEC] Locking bootloader access...",
    "0x001B1: Clearing terminal buffer...",
    // --- EXTENDED LOGS ---
    "Mounting: /dev/nvme0n1p1 to /root",
    "Checking entropy pool... 4096 bits",
    "Loading kernel module: nvidia_drm",
    "Loading kernel module: intel_rapl_msr",
    "Setting up swap space version 1, size = 16 Gib",
    "[NET] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready",
    "[NET] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready",
    "Initializing random number generator...",
    "Starting system message bus: dbus",
    "Starting Bluetooth: bluetoothd",
    "Starting Network Manager...",
    "Starting WPA Supplicant...",
    "[ACPI] ACPI Warning: _SB.PCI0.PEG0.PEGP._DSM: Argument #4 type mismatch",
    "[PCI] PciBus: 0000:00:02.0: bridge window [mem 0xd0000000-0xdfffffff]",
    "Checking file systems...",
    "fsck from util-linux 2.36.1",
    "/dev/nvme0n1p2: clean, 451820/61022208 files, 24018220/244059136 blocks",
    "Remounting root file system in read-write mode...",
    "[SYS] Setting up hostname...",
    "[SYS] Setting up loopback interface...",
    "[AUD] Loading sound driver: snd_hda_intel",
    "[AUD] ALSA device list:",
    "  #0: HDA Intel PCH at 0xdc428000 irq 147",
    "Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon",
    "Starting CUPS Printing scheduler: cupsd",
    "[PWR] Checking battery state...",
    "[PWR] Battery 0: Discharging, 89%, 03:42:12 remaining",
    "Starting Cron scheduler: cron",
    "Starting system logging: rsyslogd",
    "Starting OpenBSD Secure Shell server: sshd",
    "[SEC] AppArmor initialized.",
    "[SEC] SELinux: Disabled in config.",
    "Loading custom drivers...",
    "  > pasco_neural_bridge.ko",
    "  > pasco_visual_synth.ko",
    "  > pasco_audio_proc.ko",
    "[GPU] Vendor: NVIDIA Corporation",
    "[GPU] Renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2",
    "[GPU] Version: 4.6.0 NVIDIA 535.104.05",
    "Compiling shaders [0/120]...",
    "Compiling shaders [45/120]...",
    "Compiling shaders [120/120]... Done.",
    "Allocating VRAM buffers...",
    "  > Buffer A: 2048MB",
    "  > Buffer B: 1024MB",
    "  > Buffer C: 512MB",
    "Initializing Pasco Core Services...",
    "  > UserProfileManager: OK",
    "  > ChatHistoryManager: OK",
    "  > ContextEngine: OK",
    "  > RealismEngine: OK",
    "Checking for updates...",
    "  > Manifest fetched.",
    "  > Version: v0.8.4 (Latest)",
    "Syncing cloud presets...",
    "  > Downloaded: 0kb",
    "  > Uploaded: 0kb",
    "Applying user configuration...",
    "  > Theme: Dark",
    "  > Language: ID",
    "  > Haptics: Enabled",
    "Pre-caching assets...",
    "  > img/avatar_default.png",
    "  > img/bg_main.jpg",
    "  > sfx/startup.mp3",
    "  > sfx/click.mp3",
    "[AI] Initializing Gemini 2.5 Bridge...",
    "[AI] Handshake successful.",
    "[AI] Token limit: 4096",
    "[AI] Temperature: 0.7",
    "[AI] Safety filters: DISENGAGED",
    "[MEM] Garbage collection pass 1...",
    "[MEM] Freed 24MB.",
    "Scanning local storage for corruption...",
    "  > pasco_characters: OK",
    "  > pasco_sessions: OK",
    "  > pasco_settings: OK",
    "Initializing UI components...",
    "  > Header: Ready",
    "  > Sidebar: Ready",
    "  > ChatArea: Ready",
    "  > InputField: Ready",
    "Starting main event loop...",
    "[EVT] Listener attached: keydown",
    "[EVT] Listener attached: resize",
    "[EVT] Listener attached: visibilitychange",
    "Checking device orientation...",
    "  > Orientation: Portrait",
    "  > Dimensions: 390x844",
    "Calibrating touch sensors...",
    "  > Sensitivity: 1.0",
    "  > Multitouch: Supported",
    "Starting background workers...",
    "  > worker_data_sync.js",
    "  > worker_image_proc.js",
    "[SYS] System uptime: 4.20s",
    "[SYS] Load average: 0.15, 0.08, 0.02",
    "Clearing temporary files...",
    "  > /tmp/pasco_cache_*",
    "Unmounting temporary volumes...",
    "Flushing disk buffers...",
    "Preparing visual transition...",
    "Injecting CSS variables...",
    "  > --primary-color: #8b5cf6",
    "  > --secondary-color: #06b6d4",
    "Optimizing DOM tree...",
    "Hydrating React root...",
    "Checking biometric auth...",
    "  > Fingerprint: Match",
    "  > FaceID: Skipped",
    "Decrypting user secrets...",
    "  > master_key verified.",
    "Initializing physics engine...",
    "  > Gravity: 9.8",
    "  > Friction: 0.5",
    "Loading particle effects...",
    "  > Sparkles",
    "  > Dust",
    "  > Glitch",
    "[NET] Establishing WebSocket connection to wss://pasco.api/stream...",
    "[NET] Connection established.",
    "Subscribing to channels...",
    "  > channel: user_12345",
    "  > channel: sys_broadcast",
    "[SOC] Syncing social graph...",
    "  > Friend count: 4",
    "  > Unread DMs: 2",
    "[JOB] Checking shift status...",
    "  > No active shifts.",
    "[SHOP] Updating catalog...",
    "  > Fetched 45 items.",
    "[INV] Verifying inventory integrity...",
    "  > Integrity: 100%",
    "Initializing audio subsystem...",
    "  > Context created.",
    "  > Master volume: 1.0",
    "Loading voice models...",
    "  > TTS_Engine: Ready",
    "Checking geographical data...",
    "  > Lat/Long: [REDACTED]",
    "  > Timezone: Asia/Jakarta",
    "Synchronizing clock...",
    "  > NTP Server: time.google.com",
    "  > Offset: -0.002s",
    "Finalizing boot sequence...",
    "Allocating final resources...",
    "Checking memory pressure...",
    "  > Status: Nominal",
    "Enabling user interaction...",
    "Unlocking display...",
    "Fading in UI...",
    "Executing post-boot scripts...",
    "Running diagnostics...",
    "  > CPU: OK",
    "  > MEM: OK",
    "  > NET: OK",
    "  > STG: OK",
    "Welcome to the simulation.",
    "Remember: Reality is subjective.",
    "Initiating handshake...",
    "Sending ACK...",
    "Received SYN...",
    "Handshake complete.",
    "Starting session manager...",
    "Creating session ID...",
    "  > ID: 8f7d-2a4c-9b1e",
    "Logging start time...",
    "Mounting React components...",
    "Rendering <App />...",
    "Applying final styles...",
    "Checking dark mode preference...",
    "  > Dark mode: ON",
    "Hiding splash screen...",
    "Transferring control...",
    "Enjoy your stay.",
    "Connecting...",
    "Connected.",
    "Online.",
    "System Ready.",
    "0x001B1: Clearing terminal buffer...",
    "[SYS] Welcome to Pasco.",
    "Initializing Hub...",
    "Loading assets...",
    "Verifying integrity...",
    "Checking updates...",
    "Syncing cloud...",
    "Parsing config...",
    "Rendering mesh...",
    "Applying post-fx...",
    "Starting audio...",
    "Mounting volumes...",
    "Executing main()...",
    "Ready."
];
